### PR TITLE
feat: react-routing

### LINKED ISSUE #5: Add routing via react-router
Add the Routing functionality with the following basic routes -

1. Home
2. Signup
3. Login
4. Playlist
5. Artist
You are most welcomed to dig deeper and add more routes from the [Spotify](https://open.spotify.com/ ) site.

For a better understanding of the scope of this task, check all other issues as well.

Happy hacking 🤩!

### PR DESCRIPTION
**Pull request by jagnani73**
fixes #5

### CODE REVIEW

**Comment by saheelsapovadia** [comment]
@jagnani73 good work please read the contributing.md file about layout.js to integrate common components to avoid re-renders.

**Comment by jagnani73** [comment]
@saheelsapovadia I have made changes according to the `CONTRIBUTING.md`
Apologies!

**Comment by saheelsapovadia** [comment]
@jagnani73 Name the function component in layout.js accordingly.

**Comment by jagnani73** [comment]
@saheelsapovadia done!

**Comment by jagnani73** [comment]
@saheelsapovadia done!

**Comment by saheelsapovadia** [comment]
@jagnani73 Bro! function component in layout.js is _App()_ please correct that!

**Comment by jagnani73** [comment]
@saheelsapovadia done (-:

**Review by saheelsapovadia — APPROVED** [review]
Well done! 
Please share your experience on social media and do tag club_gamma.
Check other issues as well
Happy Hacking!

**Pull request merged**
